services:
  db:
    image: postgres
    restart: always
    volumes:
      - ~/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=worker
      - POSTGRES_PASSWORD=worker
    healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
        interval: 10s
        timeout: 3s
        retries: 3
  migrate:
    build: .
    command: python3 manage.py migrate
    depends_on:
      db:
        condition: service_healthy
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - migrate
